package zio.temporal.protobuf

import io.temporal.common.converter._
import scalapb.GeneratedFileObject
import zio.temporal.experimentalApi
import zio.temporal.protobuf.internal.ProtoFileObjectAutoLoader

object ScalapbDataConverter {

  /** Creates data converted supporting given scalapb generated types
    * @param files
    *   generated scalapb files
    * @return
    *   a [[DataConverter]] supporting given scalapb types
    */
  def make(files: Seq[GeneratedFileObject]): DataConverter =
    new DefaultDataConverter(
      // order matters!
      Seq(
        new NullPayloadConverter(),
        new ByteArrayPayloadConverter(),
        new ProtobufJsonPayloadConverter(),
        new ScalapbPayloadConverter(files),
        new JacksonJsonPayloadConverter() // falling back to jackson for primitive types
      ): _*
    )

  /** Creates data converted supporting scalapb generated types. Loads all available protobuf descriptors generated by
    * scalapb.
    *
    * @param additionalFiles
    *   additional scalapb files to add
    * @return
    *   a [[DataConverter]] supporting given scalapb types
    */
  @experimentalApi
  def makeAutoLoad(additionalFiles: Seq[GeneratedFileObject] = Nil): DataConverter = {
    val autoLoaded = ProtoFileObjectAutoLoader.loadFromClassPath(getClass.getClassLoader)
    make(autoLoaded ++ additionalFiles)
  }
}
