addSbtPlugin("org.scalameta"  % "sbt-scalafmt"      % "2.5.0")
addSbtPlugin("com.eed3si9n"   % "sbt-projectmatrix" % "0.9.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"    % "1.5.10")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"     % "2.0.8")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"          % "2.3.7")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"        % "0.5.0")
