addSbtPlugin("org.scalameta"  % "sbt-scalafmt"      % "2.4.6")
addSbtPlugin("com.eed3si9n"   % "sbt-projectmatrix" % "0.8.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"          % "2.2.21")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"    % "1.5.10")
addSbtPlugin("com.github.sbt" % "sbt-jacoco"        % "3.4.0")
