addSbtPlugin("org.scalameta"  % "sbt-scalafmt"      % "2.5.2")
addSbtPlugin("com.eed3si9n"   % "sbt-projectmatrix" % "0.10.0")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"    % "1.6.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"     % "2.1.0")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"          % "2.5.4")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"        % "0.5.0")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"     % "0.12.0")
