name: Coverage
on:
  push:
    branches: [ 'main' ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: olafurpg/setup-scala@v13
      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
          key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}
      - name: Run tests
        run: sbt coverage/jacocoAggregate
      - name: Upload test results
        uses: codecov/codecov-action@v2
        with:
          directory: ./.coverage